/**
 *  @Copyright      DoIT Cloud Consulting
 *  @Author         Jaziel Morán <jaziel.moran@doitcloud.consulting>
**/

public class BillableItemsListController {
	
    /*@AuraEnabled
    public static List<ServiceName> getServices(integer pos) {
        List<ServiceName> SN = new List<ServiceName>();
        List<Service__c> serv = new List<Service__c>([Select Name,Type__c From Service__c]);
        for(Service__c s:serv){
            ServiceName servTemp = new ServiceName();
            servTemp.servicio = s;
            servTemp.Position = pos;
            SN.add(servTemp);
        }
        return SN;
    }
    
    public class ServiceName{
        @AuraEnabled public Service__c servicio{get;set;}
        @AuraEnabled public integer Position{get;set;}
    }*/
}